### ISSUE TITLE
Code fails to run

### ISSUE THREAD

**Issue by srfrnk** [Quintor/angular-truffle-box#2]
Went over the steps.

At `ng test` or `ng serve` I get:
```
.../node_modules/@ngtools/json-schema/src/schema-tree.js:226
                this._children[name] = this._createChildProperty(name, value ? value[name] : undefined, forward ? forward.children[name] : null, propertySchema);
                                                                                                                                  ^

TypeError: Cannot read property 'glob' of null
    at ObjectSchemaTreeNode._set (.../node_modules/@ngtools/json-schema/src/schema-tree.js:226:131)
    at new ObjectSchemaTreeNode (.../node_modules/@ngtools/json-schema/src/schema-tree.js:211:14)
    at OneOfSchemaTreeNode._createChildProperty (.../node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
    at OneOfSchemaTreeNode._typesPrototype.schema.oneOf.map (.../node_modules/@ngtools/json-schema/src/schema-tree.js:163:25)
    at Array.map (native)
    at OneOfSchemaTreeNode (.../node_modules/@ngtools/json-schema/src/schema-tree.js:162:48)
    at ArraySchemaTreeNode._createChildProperty (.../node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
    at ArraySchemaTreeNode._set (.../node_modules/@ngtools/json-schema/src/schema-tree.js:288:39)
    at new ArraySchemaTreeNode (.../node_modules/@ngtools/json-schema/src/schema-tree.js:269:14)
    at ObjectSchemaTreeNode._createChildProperty (.../node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
```

Any ideas?

**Comment by pimotte** [comment]
Can you let me know versions for: 
Node.js, NPM, truffle, angular-cli, testrpc and your operating system?

**Comment by pimotte** [comment]
https://github.com/angular/angular-cli/issues/4919 and https://github.com/angular/angular-cli/issues/4207 suggest these kinds of issues are commonly caused by angular-cli config files in your home directory. Maybe that's the case for you as well?

**Comment by cisrakesh** [comment]
Any solutions ? https://github.com/angular/angular-cli/issues/4207  and https://github.com/angular/angular-cli/issues/4919 , but no solutions works.

**Comment by pimotte** [comment]
https://github.com/angular/angular-cli/issues/7884 and https://github.com/angular/angular-cli/issues/6698 also look relevant.

**Comment by srfrnk** [comment]
I did find a ```.angular-cli.json``` under my home folder and deleted that.
Works great now. 10x.

**Comment by cisrakesh** [comment]
deleting .angular-cli.json give this error 
Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (/var/www/html/angcliapp/node_modules/@angular/cli/tasks/serve.js:51:63)
    at check_port_1.checkPort.then.port (/var/www/html/angcliapp/node_modules/@angular/cli/commands/serve.js:121:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by pimotte** [comment]
To be clear, you shouldn't be deleting the .angular-cli.json in the project itself, but any that remains in your home directory. I also recommend reinstalling all dependencies and checking out everything again

**Comment by cisrakesh** [comment]
Had searched on my harddisk , hasn't found .angular-cli.json on any other place . Still getting this error 
sudo ng serve
/var/www/html/angappcli/node_modules/@ngtools/json-schema/src/schema-tree.js:226
                this._children[name] = this._createChildProperty(name, value ? value[name] : undefined, forward ? forward.children[name] : null, propertySchema);
                                                                                                                                   ^

TypeError: Cannot read property 'glob' of null
    at ObjectSchemaTreeNode._set (/var/www/html/angappcli/node_modules/@ngtools/json-schema/src/schema-tree.js:226:132)
    at new ObjectSchemaTreeNode (/var/www/html/angappcli/node_modules/@ngtools/json-schema/src/schema-tree.js:211:14)
    at OneOfSchemaTreeNode._createChildProperty (/var/www/html/angappcli/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
    at OneOfSchemaTreeNode._typesPrototype.schema.oneOf.map (/var/www/html/angappcli/node_modules/@ngtools/json-schema/src/schema-tree.js:163:25)
    at Array.map (<anonymous>)
    at OneOfSchemaTreeNode (/var/www/html/angappcli/node_modules/@ngtools/json-schema/src/schema-tree.js:162:48)
    at ArraySchemaTreeNode._createChildProperty (/var/www/html/angappcli/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
    at ArraySchemaTreeNode._set (/var/www/html/angappcli/node_modules/@ngtools/json-schema/src/schema-tree.js:288:39)
    at new ArraySchemaTreeNode (/var/www/html/angappcli/node_modules/@ngtools/json-schema/src/schema-tree.js:269:14)
    at ObjectSchemaTreeNode._createChildProperty (/var/www/html/angappcli/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)

**Comment by pimotte** [comment]
Check if /root/.angular-cli.json exists. 

I also recommend against running ng serve with sudo, that seems like a security risk.

**Comment by cisrakesh** [comment]
checked with locate -i ".angular-cli.json"  , but haven't find any search result

**Comment by pimotte** [comment]
And if you do the instructions from scratch without using sudo?
