### ISSUE TITLE
Unbox failing on windows 10

### ISSUE THREAD

**Issue by ashutoshsinghparmar** [Quintor/angular-truffle-box#67]
Hello Team,

I tried unboxing as well as directly downloading the content and then installing using npm install.

`npm install` is failing.

![image](https://user-images.githubusercontent.com/11618392/100379893-ba326280-303b-11eb-9531-edd83d41c157.png)

Following is the log for the same:

2733 verbose stack Error: sha3@1.2.3 install: `node-gyp rebuild`
2733 verbose stack Exit status 1
2733 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
2733 verbose stack     at EventEmitter.emit (events.js:314:20)
2733 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
2733 verbose stack     at ChildProcess.emit (events.js:314:20)
2733 verbose stack     at maybeClose (internal/child_process.js:1047:16)
2733 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
2734 verbose pkgid sha3@1.2.3
2735 verbose cwd E:\git-not\truffle-angular-box
2736 verbose Windows_NT 10.0.18363
2737 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
2738 verbose node v14.13.0
2739 verbose npm  v6.14.8
2740 error code ELIFECYCLE
2741 error errno 1
2742 error sha3@1.2.3 install: `node-gyp rebuild`
2742 error Exit status 1
2743 error Failed at the sha3@1.2.3 install script.
2743 error This is probably not a problem with npm. There is likely additional logging output above.
2744 verbose exit [ 1, true ]

System Information:
Windows 10
windows-build-tools@5.2.2

**Comment by niharika412** [comment]
hey @ashu12318 did you manage to solve it?
